spring.application.name=FirstWebApplication
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.security.user.name=rajesh
spring.security.user.password=1234

#trun off spring boot banner
spring.main.banner-mode=off

#reduce logging level set logging level to warn
logging.level.root=warn